FROM ubuntu:24.04
RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update -qq \
 && apt-get install -y apt-utils \
 && apt-get install -y --no-install-recommends \
      build-essential cmake ninja-build git ca-certificates \
      mingw-w64 p7zip-full \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
